### ISSUE TITLE
TempMail Ban my ip

### ISSUE THREAD

**Issue by aoGFX** [RyuzakiH/Temp-Mail-API#1]
Temp mail will ban any ip if u send much requests :(
Can u add Proxy Option Please <3
Thank You.

**Comment by RyuzakiH** [comment]
Sorry for late reply, I'll add it today.

**Comment by RyuzakiH** [comment]
Sorry for late reply, I'll add it today.

**Comment by RyuzakiH** [comment]
Added Proxy Option.
Try it and contact me if there's a problem.
Have a good day :)
